name: ZAP Full Scan

on: [push,pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Apply migrations
        run: |
         python ./pygoat/manage.py migrate
      - name: run development server on localhost
        run: |
         python ./pygoat/manage.py runserver
     
  WaitForResponse:
  
    runs-on: ubuntu-latest
    steps:
      - name: Wait for response server
        uses: nev7n/wait_for_response@v1
        with:
         url: 'http://127.0.0.1:8000'
         responseCode: 302
         timeout: 60000
         interval: 500
     
  OWASPZap:
  
    needs: WaitForResponse
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'http://127.0.0.1:8000'
